apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
type: Opaque
stringData:
  azurestorageaccountname: PLACEHOLDER_NAME
  azurestorageaccountkey: PLACEHOLDER_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gym-db
  template:
    metadata:
      labels:
        app: gym-db
    spec:
      securityContext:
        # Optimized for Azure File SMB permissions
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      containers:
      - name: mysql
        image: gymappregistryunique99.azurecr.io/gym-db:v1
        args:
          - "--innodb_use_native_aio=0"
          - "--innodb_doublewrite=0"
          - "--innodb_flush_method=fsync"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "gymrootpass"
        - name: MYSQL_DATABASE
          value: "gymapp"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql 
      volumes:
      - name: mysql-storage
        azureFile:
          secretName: azure-storage-secret
          # SWITCHED TO NEW SHARE TO AVOID PREVIOUS CORRUPTION
          shareName: gym-db-v4 
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: gym-db-service
spec:
  selector:
    app: gym-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP