apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gym-app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: mygym.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gym-frontend-service
            port:
              number: 80