apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gym-app-ingress
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: azure-application-gateway
  tls:
  - hosts:
    - __DOMAIN__
    secretName: __TLS_SECRET__
  rules:
  - host: __DOMAIN__
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gym-frontend-service
            port:
              number: 80