name: 1. Deploy Database
on:
  repository_dispatch:
    types: [deploy-gym-db] 
  push:
    branches: [main]
    paths: ['src/db/**', 'kube/db-deploy.yaml'] 
  workflow_dispatch:
    inputs:
      env:
        description: 'which env to deploy'
        required: true
        default: 'dev'

jobs:
  db-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

     
      - name: Set Environment Name
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "DEPLOY_ENV=${{ github.event.client_payload.env }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "push" ]; then
            # Push logic sathi tuza default 'dev' dharu
            echo "DEPLOY_ENV=dev" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=${{ github.event.inputs.env }}" >> $GITHUB_ENV
          fi

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      
      - name: Set Dynamic Names
        run: |
          # Azure resources chi naave environment pramane automatic badlatil
          echo "ACR_NAME=gym${{ env.DEPLOY_ENV }}acr" >> $GITHUB_ENV
          echo "RG_NAME=gym-app-${{ env.DEPLOY_ENV }}-rg" >> $GITHUB_ENV
          echo "CLUSTER_NAME=gym-${{ env.DEPLOY_ENV }}-aks" >> $GITHUB_ENV

      - name: Build and Push DB Image
        run: |
          az acr login --name ${{ env.ACR_NAME }}
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/gym-db:${{ github.sha }} ./src/db
          docker push ${{ env.ACR_NAME }}.azurecr.io/gym-db:${{ github.sha }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RG_NAME }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Deploy to K8s
        run: |
          # Image naav YAML madhye dynamic update karne
          sed -i "s|image:.*|image: ${{ env.ACR_NAME }}.azurecr.io/gym-db:${{ github.sha }}|" kube/db-deploy.yaml
          kubectl apply -f kube/db-deploy.yaml
          kubectl rollout status deployment/gym-db --timeout=120s

      - name: Trigger Backend Deployment
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}
          event-type: deploy-gym-backends 
          client-payload: '{"env": "${{ env.DEPLOY_ENV }}"}'    